### ISSUE TITLE
Link StackTrace with git

### ISSUE THREAD

**Issue by kewang** [kewang/logback-redmine-appender#4]
From #1

**Comment by qrtt1** [comment]
有幾種實踐方式
1. 在 logger 本身寫入完整的資訊（但會把 logger 變複雜）
2. 改logger 寫必要資訊（revision 與檔名跟行號），改 redmine 的顯示（真的擴充 redmine 或用 browser plugin 修飾 redmine 呈現方式）

**Comment by kewang** [comment]
目前是打算用類似第二種的方式來撰寫。至於改 redmine 的顯示倒也不必，目前是打算先支援 GitHub, GitLab, Bitbucket 這些有畫面的。logger 在傳給 redmine 時會變成下面這種方式

``` java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 5
    at tw.kewang.Demo.main(<a href="https://github.com/example/example/blob/master/src/main/java/tw/kewang/Demo.java#L8">Demo.java:8</a>)
```

另外我是希望像這類的資訊應該可以另開一個 `logback-appender-extras`，然後外掛進去讓各種 appender 都可以用。

**Comment by kewang** [comment]
剛已經寫出來這一段 ( 7fc849c )了，可是突然想到這樣子搞的話，我要自己重做一套 stacktrace Orz

``` java
    /**
     * Convert com.example.Test(Test.java: 15) class to com/example/Test.java#L15
     */
    private String convertClassToNavigate(StackTraceElement elem) {
        String[] classNameArray = elem.getClassName().split("\\.");

        classNameArray[classNameArray.length - 1] = elem.getFileName();

        String result = "";

        for (String className : classNameArray) {
            result += className + "/";
        }

        result = result.substring(0, result.length() - 1);

        result += "#L" + elem.getLineNumber();

        return result;
    }
```

**Comment by kewang** [comment]
打算先用簡單的方式，上面放 link 下面放 stacktrace，先暫時不理重寫一套 stacktrace 的問題。如果是 com.intellij / org.eclipse 這類，應該會放在 blacklist 裡面不顯示 link。

以下為顯示方式

---

## link
- <a href="#">tw.kewang.logback.appender.AppTest.testApp(AppTest.java:16)</a>

## stacktrace

``` java
2016-07-26 23:44:57.987 [main] ERROR tw.kewang.logback.appender.AppTest - Caught Exception: 
java.lang.NullPointerException: null
    at tw.kewang.logback.appender.AppTest.testApp(AppTest.java:16)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```
